# AUTO-GENERATED REGRESSION TEST
# ----------------------------------------
# Source trace: 9f6f6ecb-5798-43f7-9231-c1bb1123cc1f
# Failure type: unknown
# Model: unknown
# Generated by: TraceOps Lite
#
# This file was automatically generated
# from a production failure report.
#
# DO NOT EDIT MANUALLY
# ----------------------------------------

import pytest

from deepeval import assert_test
from deepeval.test_case import LLMTestCase

from deepeval.metrics import AnswerRelevancyMetric


@pytest.mark.regression
def test_regression_9f6f6ecb():
    """
    Regression test generated from
    production trace:

    9f6f6ecb-5798-43f7-9231-c1bb1123cc1f

    Failure type:
    unknown
    """

    test_case = LLMTestCase(
        input="unknown",
        actual_output="unknown",
        retrieval_context=[],
    )

    metric = AnswerRelevancyMetric(threshold=0.7)

    assert_test(
        test_case,
        [metric],
    )


# ---- Metadata ----------------------------------

TRACE_ID = "9f6f6ecb-5798-43f7-9231-c1bb1123cc1f"

FAILURE_TYPE = "unknown"

MODEL = "unknown"

SOURCES = []
