# AUTO-GENERATED REGRESSION TEST
# ----------------------------------------
# Source trace: unknown
# Failure type: bad_retrieval
# Model: mistralai/mistral-7b-instruct-v0.1
# Generated by: TraceOps Lite
#
# This file was automatically generated
# from a production failure report.
#
# DO NOT EDIT MANUALLY
# ----------------------------------------

import pytest

from deepeval import assert_test
from deepeval.test_case import LLMTestCase

from deepeval.metrics import FaithfulnessMetric


@pytest.mark.regression
def test_regression_unknown():
    """
    Regression test generated from
    production trace:

    unknown

    Failure type:
    bad_retrieval
    """

    test_case = LLMTestCase(
        input="unknown",
        actual_output="",
        retrieval_context=[],
    )

    metric = FaithfulnessMetric(threshold=0.8)

    assert_test(
        test_case,
        [metric],
    )


# ---- Metadata ----------------------------------

TRACE_ID = "unknown"

FAILURE_TYPE = "bad_retrieval"

MODEL = "mistralai/mistral-7b-instruct-v0.1"

SOURCES = []
