# AUTO-GENERATED REGRESSION TEST
# ----------------------------------------
# Source trace: ece5944b-255d-400f-a305-5e5080d11ef2
# Failure type: unknown
# Model: unknown
# Generated by: TraceOps Lite
#
# This file was automatically generated
# from a production failure report.
#
# DO NOT EDIT MANUALLY
# ----------------------------------------

import pytest

from deepeval import assert_test
from deepeval.test_case import LLMTestCase

from deepeval.metrics import AnswerRelevancyMetric


@pytest.mark.regression
def test_regression_ece5944b():
    """
    Regression test generated from
    production trace:

    ece5944b-255d-400f-a305-5e5080d11ef2

    Failure type:
    unknown
    """

    test_case = LLMTestCase(
        input="unknown",
        actual_output="unknown",
        retrieval_context=[],
    )

    metric = AnswerRelevancyMetric(threshold=0.7)

    assert_test(
        test_case,
        [metric],
    )


# ---- Metadata ----------------------------------

TRACE_ID = "ece5944b-255d-400f-a305-5e5080d11ef2"

FAILURE_TYPE = "unknown"

MODEL = "unknown"

SOURCES = []
