# AUTO-GENERATED REGRESSION TEST
# ----------------------------------------
# Source trace: 7d861551-c663-4549-815a-23083c6e35e6
# Failure type: unknown
# Model: unknown
# Generated by: TraceOps Lite
#
# This file was automatically generated
# from a production failure report.
#
# DO NOT EDIT MANUALLY
# ----------------------------------------

import pytest

from deepeval import assert_test
from deepeval.test_case import LLMTestCase

from deepeval.metrics import AnswerRelevancyMetric


@pytest.mark.regression
def test_regression_7d861551():
    """
    Regression test generated from
    production trace:

    7d861551-c663-4549-815a-23083c6e35e6

    Failure type:
    unknown
    """

    test_case = LLMTestCase(
        input="unknown",
        actual_output="unknown",
        retrieval_context=[],
    )

    metric = AnswerRelevancyMetric(threshold=0.7)

    assert_test(
        test_case,
        [metric],
    )


# ---- Metadata ----------------------------------

TRACE_ID = "7d861551-c663-4549-815a-23083c6e35e6"

FAILURE_TYPE = "unknown"

MODEL = "unknown"

SOURCES = []
